name: app_oint9
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  intl: ^0.19.0
  url_launcher: ^6.2.4
  share_plus: ^7.2.1
  flutter_contacts: ^1.1.7+1
  permission_handler: ^11.3.0
  logger: ^2.0.2+1
  firebase_core_platform_interface: ^5.0.0
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.2.1
  fake_cloud_firestore: ^2.4.8
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true  # Enable code generation for localization 