name: app_oint9
description: A modern appointment scheduling system
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  intl: any
  cloud_firestore: any
  firebase_core: any
  firebase_auth: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
