<<<<<<< HEAD
name: app_oint9
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
=======
name: app_oint
description: Your appointment & task manager
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
>>>>>>> e7105b1f419548c2d80209a9eca410177f0a8a53

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
<<<<<<< HEAD
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  intl: ^0.19.0
  url_launcher: ^6.2.4
  share_plus: ^7.2.1
  flutter_contacts: ^1.1.7+1
  permission_handler: ^11.3.0
  logger: ^2.0.2+1
  firebase_core_platform_interface: ^5.0.0
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.2.1
  fake_cloud_firestore: ^2.4.8
  json_annotation: ^4.9.0
  fl_chart: ^0.66.1
  csv: ^5.1.1
  go_router: ^14.1.3
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.5.3
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true  # Enable code generation for localization 
=======
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.2
  sign_in_with_apple: ^7.0.1
  flutter_riverpod: ^2.4.9
  http: ^1.2.1
  intl: ^0.19.0
  url_launcher: ^6.3.1
  share_plus: ^11.0.0
  csv: ^6.0.0
  fl_chart: ^1.0.0
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  flutter_stripe: ^11.5.0
  logging: ^1.2.0
  firebase_core: ^3.13.1
  flutter_dotenv: ^5.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dev_dependencies:
  build_runner: ^2.4.15
  mockito: ^5.4.6

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/l10n/ 
>>>>>>> e7105b1f419548c2d80209a9eca410177f0a8a53
