// Mocks generated by Mockito 5.4.6 from annotations
// in app_oint9/test/screens/appointment_edit_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:app_oint9/models/appointment.dart' as _i4;
import 'package:app_oint9/services/appointments_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AppointmentsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppointmentsService extends _i1.Mock
    implements _i2.AppointmentsService {
  MockAppointmentsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> createAppointment(_i4.Appointment? appointment) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAppointment,
          [appointment],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #createAppointment,
            [appointment],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> updateAppointment(_i4.Appointment? appointment) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAppointment,
          [appointment],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAppointment(String? appointmentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAppointment,
          [appointmentId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.Appointment>> getAppointmentsStream() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAppointmentsStream,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.Appointment>>.empty(),
      ) as _i3.Stream<List<_i4.Appointment>>);

  @override
  _i3.Future<_i4.Appointment?> getAppointment(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAppointment,
          [id],
        ),
        returnValue: _i3.Future<_i4.Appointment?>.value(),
      ) as _i3.Future<_i4.Appointment?>);
}
