name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Firebase
      run: npm install -g firebase-tools
    - name: Authenticate with Firebase
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $GITHUB_WORKSPACE/firebase.json
      run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > firebase.json
    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting 